const TITLE = {
  0: 'Bạn chắc chắn', // 0
  1: 'Thành công', // 1
  2: 'Đã hoàn thành', // 2
  3: 'Thất bại', // 3
  4: 'Thông báo', // 4
  5: 'Không thành công', // 5
  6: 'Cảnh báo', //6
  errConnect: 'Lỗi kết nối'
};

const CONTENT = {
  0: 'Bạn có muốn chuyển trạng thái bàn',
  1: 'sang bàn đang dùng?',
  2: 'sang bàn trống?',
  3: 'đã chuyển trạng thái bàn đang dùng',
  4: 'đã chuyển trạng thái bàn trống',
  5: 'chuyển trạng thái không thành công',
  6: 'Muốn hủy thanh toán order',
  7: 'này?',
  8: 'Order',
  9: 'đã hủy thanh toán',
  10: 'hủy thất bại, vui lòng thử lại',
  11: 'Bàn này không có order',
  12: 'Bàn này đã được thanh toán',
  13: 'Muốn chuyển bàn',
  14: 'Thông tin đặt bàn đã được xác nhận',
  15: 'Thông tin đặt bàn đã được hủy',
  16: 'Xác nhận thành công',
  17: 'Muốn xác nhận thông tin đặt bàn này ?',
  18: 'Muốn hủy đặt bàn này ?',
  19: 'Xác nhận khách đã vào bàn ?',
  20: 'Order này đã được thanh toán',
  21: 'Bạn muốn giao món',
  22: 'Bạn muốn hủy món',
  23: 'Món',
  24: 'đã được hủy',
  25: 'đã được giao',
  26: 'Bạn chưa đăng ký số suất. Vui lòng đăng ký trước khi vào chọn món',
  27: 'Muốn gọi món cho order này?',
  28: 'Order đã được gọi món',
  29: 'Gọi món thất bại',
  30: 'Muốn hủy order này?',
  31: 'Order đã được hủy',
  32: 'Xác nhận thanh toán',
  33: 'Vui lòng nhập tiền khách đưa',
  34: 'Bàn',
  35: 'Thanh toán thành công',
  36: 'Thanh toán không thành công. Vui lòng kiểm tra lại!..',
  37: 'Bạn muốn lưu thông tin order này',
  38: 'Lưu thông tin order thất bại',
  39: 'Lưu thông tin order thành công',
  40: 'Bạn muốn huỷ đơn hàng này',
  41: 'Bạn muốn giao hàng cho đơn hàng này',
  42: 'Bạn đã huỷ order thành công',
  43: 'Bạn đã huỷ order thất bại',
  44: 'Bạn đã giao hàng order thành công',
  45: 'Bạn đã giao hàng order thất bại',
  46: 'Chọn danh sách đặt bàn này?',
  47: 'Bạn chắc chắn muốn quay về.',
  48: 'Thanh toán thành công',
  49: 'Bàn này chưa gọi món!',
  50: 'Tổng số ghế nhỏ hơn số khách.Bạn có chắc chắn chọn những bàn này?',
  51: 'Còn quá sớm để xác nhận khách vào bàn. Bạn có chắc chắn xác nhận?',
  52: 'Xác nhận vào bàn',
  53: 'Bạn muốn lưu và thanh toán cho order này?',
  54: 'Bạn muốn khôi phục order?',
  55: 'Bạn không còn ca làm khả dụng hôm nay Bạn vẫn muốn check-in?',
  56: 'Vui lòng xác nhận check-in để tiếp tục sử dụng Omenu',
  57: 'Không có ca làm khả dụng để check-in',
  58: 'Bạn đang trong ca làm việc',
  59: 'Khôi phục order thành công',
  60: 'Khôi phục order thất bại. Vui lòng thử lại sau',
  61: 'Bạn muốn chuyển order này sang bàn khác',
  62: 'Xử lý yêu cầu thất bại. Vui lòng thử lại sau',
  63: 'Xác nhận khách vào bàn và tạo order',
  64: 'Bàn này có order chưa thanh toán. Không thể chuyển bàn trống. Vui lòng kiểm tra lại',
  65: 'Xác nhận các món của order này?',
  66: 'Order này đã gửi tới bếp/bar',
  67: 'đã xác nhận',
  68: 'Muốn xác nhận món',
  69: 'Xác nhận khách vào bàn thành công. Thông báo đã được chuyển tới khách hàng',
  70: 'Xác nhận khách vào bàn thành công. Thông báo có thể chưa được chuyển tới khách hàng',
  71: 'Bạn muốn xác nhận món',
  72: 'đã được xác nhận với bếp/bar',
  73: 'Từ chối yêu cầu vào bàn thành công. Thông báo đã được chuyển tới khách hàng',
  74: 'Xác nhận khách vào bàn thành công. Thông báo có thể chưa được chuyển tới khách hàng',
  smsContact: 'Thông tin liên hệ đã được gửi đi.',
  errPrint: 'Kết nối máy in của bạn đang gặp vấn đề.\n Bạn có muốn tiếp tục thao tác?',
  readyPrint: 'Đã kết nối tới máy in bếp/bar',
  dialogWarning: 'Vui lòng kiểm tra lại thông tin gọi món và thanh toán. \n Nếu đã hoàn tất thanh toán, vui lòng chuyển qua bàn trống để tiếp tục.',
  confirmSuccess: 'Xác nhận thành công món'
};

export default { TITLE, CONTENT };
