require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'OmenuStaff' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


  target 'OmenuStaffTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.74.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'OmenuStaff-tvOS' do
  # Pods for OmenuStaff-tvOS

  target 'OmenuStaff-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
