// start
const START_SCREEN = 'START_SCREEN';

// auth
const LOGIN = 'LOGIN';
const SELECT_USER = 'SELECT_USER';

// tab
const BOTTOM_TAB = 'BOTTOM_TAB';
const HOME = 'HOME';
const ODER_TABLE = 'ODER_TABLE';
const TAKE_AWAY = 'TAKE_AWAY';
const CONFIRM = 'CONFIRM';
const ORDER_FOOD_WITHOUT_TABLE = 'ORDER_FOOD_WITHOUT_TABLE';
const TAB_WITH_CHECK_IN = 'TAB_WITH_CHECK_IN';

// stack
const NOTIFICATION = 'NOTIFICATION';
const USER_DETAIL = 'USER_DETAIL';
const BOOK_TABLE = 'BOOK_TABLE';
const BOOK_TABLE_DETAIL = 'BOOK_TABLE_DETAIL';
const FOOD_CATEGORY = 'FOOD_CATEGORY';
const ORDER_FOOD = 'ORDER_FOOD';
const FOOD_ORDERED = 'FOOD_ORDERED';
const ORDER_PAYMENT = 'ORDER_PAYMENT';
const PAYMENT = 'PAYMENT';
const PAYMENT_DETAIL = 'PAYMENT_DETAIL';
const INVOICE = 'INVOICE';
const EDIT_FOOD = 'EDIT_FOOD';
const LIST_BILL = 'LIST_BILL';
const REPORT_DETAIL = 'REPORT_DETAIL';
const TAKEAWAY_PAYMENT = 'TAKEAWAY_PAYMENT';
const TAKEAWAY_CATEGORY = 'TAKEAWAY_CATEGORY';
const TAKEAWAY_FOOD = 'TAKEAWAY_FOOD';
const BOOK_SEARCH_TABLE = 'BOOK_SEARCH_TABLE';
const ORDER_DETAILS = 'ORDER_DETAILS';
const TAKEAWAY_SEARCH = 'TAKEAWAY_SEARCH';
const BOOK_TABLE_EDIT = 'BOOK_TABLE_EDIT';
const PAY_ONEBYONE = 'PAY_ONEBYONE';
const SEARCH_FOOD = 'SEARCH_FOOD';
const CHECK_IN_OUT = 'CHECK_IN_OUT';
const PRINT_BILL_BLUETOOTH = 'PRINT_BILL_BLUETOOTH';
const REPORT = 'REPORT';
const CONTACT = 'CONTACT';

const MANAGE = 'MANAGE'
const MANAGEFOOD = 'MANAGEFOOD'
const HISTORYPAYMENT = 'HISTORYPAYMENT'
const HISTORYPAYMENTDETAIL = 'HISTORYPAYMENTDETAIL'
const ADDFOOD = 'ADDFOOD'
const EDITFOOD = 'EDITFOOD'
const FOODDETAIL = 'FOODDETAIL'

export {
  // PRINT_BILL_BLUETOOTH,
  START_SCREEN,
  LOGIN,
  SELECT_USER,
  BOTTOM_TAB,
  HOME,
  ODER_TABLE,
  TAKE_AWAY,
  CONFIRM,
  NOTIFICATION,
  USER_DETAIL,
  BOOK_TABLE,
  BOOK_TABLE_DETAIL,
  FOOD_CATEGORY,
  ORDER_FOOD,
  FOOD_ORDERED,
  ORDER_PAYMENT,
  PAYMENT,
  PAYMENT_DETAIL,
  INVOICE,
  EDIT_FOOD,
  LIST_BILL,
  REPORT_DETAIL,
  TAKEAWAY_PAYMENT,
  TAKEAWAY_CATEGORY,
  TAKEAWAY_FOOD,
  BOOK_SEARCH_TABLE,
  ORDER_DETAILS,
  TAKEAWAY_SEARCH,
  BOOK_TABLE_EDIT,
  PAY_ONEBYONE,
  SEARCH_FOOD,
  ORDER_FOOD_WITHOUT_TABLE,
  CHECK_IN_OUT,
  TAB_WITH_CHECK_IN,
  REPORT,
  CONTACT,
  MANAGE,
  MANAGEFOOD,
  HISTORYPAYMENT,
  HISTORYPAYMENTDETAIL,
  ADDFOOD,
  EDITFOOD,
  FOODDETAIL
};
