export default {
  GET_ORDER: 'GET_ORDER',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_FAIL: 'GET_ORDER_FAIL',
  GET_ORDER_UNMOUNT: 'GET_ORDER_UNMOUNT',
  UPDATE_PROCESS_ALL: 'UPDATE_PROCESS_ALL',
  UPDATE_PROCESS: 'UPDATE_PROCESS',

  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_PROCESSING_SUCCESS: 'ORDER_PROCESSING_SUCCESS',
  ORDER_PROCESSING_FAIL: 'ORDER_PROCESSING_FAIL',
  ORDER_PROCESSING_UNMOUNT: 'ORDER_PROCESSING_UNMOUNT',

  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_CANCEL_SUCCESS: 'ORDER_CANCEL_SUCCESS',
  ORDER_CANCEL_FAIL: 'ORDER_CANCEL_FAIL',
  ORDER_CANCEL_UNMOUNT: 'ORDER_CANCEL_UNMOUNT',

  NOTIFICATION: 'NOTIFICATION',
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_FAIL: 'NOTIFICATION_FAIL',
  NOTIFICATION_UNMOUNT: 'NOTIFICATION_UNMOUNT',

  GET_PRINT_CHICKEN_BAR: 'GET_PRINT_CHICKEN_BAR',
  GET_PRINT_CHICKEN_BAR_SUCCESS: 'GET_PRINT_CHICKEN_BAR_SUCCESS',
  GET_PRINT_CHICKEN_BAR_FAIL: 'GET_PRINT_CHICKEN_BAR_FAIL',
  GET_PRINT_CHICKEN_BAR_UNMOUNT: 'GET_PRINT_CHICKEN_BAR_UNMOUNT',

  GET_PRINT_CHICKEN_BAR_BY_ID: 'GET_PRINT_CHICKEN_BAR_BY_ID',
  GET_PRINT_CHICKEN_BAR_BY_ID_SUCCESS: 'GET_PRINT_CHICKEN_BAR_BY_ID_SUCCESS',
  GET_PRINT_CHICKEN_BAR_BY_ID_FAIL: 'GET_PRINT_CHICKEN_BAR_BY_ID_FAIL',
  GET_PRINT_CHICKEN_BAR_BY_ID_UNMOUNT: 'GET_PRINT_CHICKEN_BAR_BY_ID_UNMOUNT',


  RECEIPT_COOK: 'RECEIPT_COOK',
  RECEIPT_COOK_SUCCESS: 'RECEIPT_COOK_SUCCESS',
  RECEIPT_COOK_FAIL: 'RECEIPT_COOK_FAIL',
  RECEIPT_COOK_UNMOUNT: 'RECEIPT_COOK_UNMOUNT',

};
